2025-06-18 01:53:55,281 INFO: Received request for avatar: ldrshza.png [in /var/www/proobrazovanie/data/www/ruproobrazovanie.ru/app/routes.py:640]
2025-06-18 01:53:55,282 INFO: Looking for avatar at: ./uploaded_files/avatars/ldrshza.png [in /var/www/proobrazovanie/data/www/ruproobrazovanie.ru/app/routes.py:643]
2025-06-18 01:53:55,282 INFO: Serving ldrshza.png with MIME type: image/png [in /var/www/proobrazovanie/data/www/ruproobrazovanie.ru/app/routes.py:663]
2025-06-18 01:54:21,433 INFO: Microblog startup [in /var/www/proobrazovanie/data/www/ruproobrazovanie.ru/app/__init__.py:58]
2025-06-18 01:54:21,464 INFO: Microblog startup [in /var/www/proobrazovanie/data/www/ruproobrazovanie.ru/app/__init__.py:58]
2025-06-18 01:54:21,595 INFO: Microblog startup [in /var/www/proobrazovanie/data/www/ruproobrazovanie.ru/app/__init__.py:58]
2025-06-18 01:54:21,654 INFO: Microblog startup [in /var/www/proobrazovanie/data/www/ruproobrazovanie.ru/app/__init__.py:58]
2025-06-18 01:54:23,000 ERROR: Exception on /avatars/vas95.png [GET] [in /var/www/proobrazovanie/data/www/ruproobrazovanie.ru/venv/lib/python3.8/site-packages/flask/app.py:838]
Traceback (most recent call last):
  File "/var/www/proobrazovanie/data/www/ruproobrazovanie.ru/venv/lib/python3.8/site-packages/flask/app.py", line 1473, in wsgi_app
    response = self.full_dispatch_request()
  File "/var/www/proobrazovanie/data/www/ruproobrazovanie.ru/venv/lib/python3.8/site-packages/flask/app.py", line 882, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/var/www/proobrazovanie/data/www/ruproobrazovanie.ru/venv/lib/python3.8/site-packages/flask/app.py", line 880, in full_dispatch_request
    rv = self.dispatch_request()
  File "/var/www/proobrazovanie/data/www/ruproobrazovanie.ru/venv/lib/python3.8/site-packages/flask/app.py", line 865, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**view_args)  # type: ignore[no-any-return]
  File "/var/www/proobrazovanie/data/www/ruproobrazovanie.ru/app/routes.py", line 642, in uploaded_avatar
    if not os.path.exists(full_path_for_log):
NameError: name 'full_path_for_log' is not defined
2025-06-18 01:54:23,000 ERROR: Exception on /avatars/ldrshza.png [GET] [in /var/www/proobrazovanie/data/www/ruproobrazovanie.ru/venv/lib/python3.8/site-packages/flask/app.py:838]
Traceback (most recent call last):
  File "/var/www/proobrazovanie/data/www/ruproobrazovanie.ru/venv/lib/python3.8/site-packages/flask/app.py", line 1473, in wsgi_app
    response = self.full_dispatch_request()
  File "/var/www/proobrazovanie/data/www/ruproobrazovanie.ru/venv/lib/python3.8/site-packages/flask/app.py", line 882, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/var/www/proobrazovanie/data/www/ruproobrazovanie.ru/venv/lib/python3.8/site-packages/flask/app.py", line 880, in full_dispatch_request
    rv = self.dispatch_request()
  File "/var/www/proobrazovanie/data/www/ruproobrazovanie.ru/venv/lib/python3.8/site-packages/flask/app.py", line 865, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**view_args)  # type: ignore[no-any-return]
  File "/var/www/proobrazovanie/data/www/ruproobrazovanie.ru/app/routes.py", line 642, in uploaded_avatar
    if not os.path.exists(full_path_for_log):
NameError: name 'full_path_for_log' is not defined
2025-06-18 01:55:22,191 INFO: Microblog startup [in /var/www/proobrazovanie/data/www/ruproobrazovanie.ru/app/__init__.py:58]
2025-06-18 01:55:22,279 INFO: Microblog startup [in /var/www/proobrazovanie/data/www/ruproobrazovanie.ru/app/__init__.py:58]
2025-06-18 01:55:22,397 INFO: Microblog startup [in /var/www/proobrazovanie/data/www/ruproobrazovanie.ru/app/__init__.py:58]
2025-06-18 01:55:22,467 INFO: Microblog startup [in /var/www/proobrazovanie/data/www/ruproobrazovanie.ru/app/__init__.py:58]
2025-06-18 01:57:16,170 INFO: Microblog startup [in /var/www/proobrazovanie/data/www/ruproobrazovanie.ru/app/__init__.py:58]
2025-06-18 01:57:16,288 INFO: Microblog startup [in /var/www/proobrazovanie/data/www/ruproobrazovanie.ru/app/__init__.py:58]
2025-06-18 01:57:16,339 INFO: Microblog startup [in /var/www/proobrazovanie/data/www/ruproobrazovanie.ru/app/__init__.py:58]
2025-06-18 01:57:16,444 INFO: Microblog startup [in /var/www/proobrazovanie/data/www/ruproobrazovanie.ru/app/__init__.py:58]
2025-06-18 01:57:22,623 INFO: Received request for avatar: ldrshza.png [in /var/www/proobrazovanie/data/www/ruproobrazovanie.ru/app/routes.py:643]
2025-06-18 01:57:22,624 INFO: Looking for avatar at: ./uploaded_files/avatars/ldrshza.png [in /var/www/proobrazovanie/data/www/ruproobrazovanie.ru/app/routes.py:645]
2025-06-18 01:57:22,624 INFO: Attempting to serve ldrshza.png via send_from_directory. [in /var/www/proobrazovanie/data/www/ruproobrazovanie.ru/app/routes.py:655]
2025-06-18 01:57:22,619 INFO: Received request for avatar: vas95.png [in /var/www/proobrazovanie/data/www/ruproobrazovanie.ru/app/routes.py:643]
2025-06-18 01:57:22,624 ERROR: Error from send_from_directory for ldrshza.png: 404 Not Found: The requested URL was not found on the server. If you entered the URL manually please check your spelling and try again. [in /var/www/proobrazovanie/data/www/ruproobrazovanie.ru/app/routes.py:658]
2025-06-18 01:57:22,624 INFO: Looking for avatar at: ./uploaded_files/avatars/vas95.png [in /var/www/proobrazovanie/data/www/ruproobrazovanie.ru/app/routes.py:645]
2025-06-18 01:57:22,624 INFO: Attempting to serve vas95.png via send_from_directory. [in /var/www/proobrazovanie/data/www/ruproobrazovanie.ru/app/routes.py:655]
2025-06-18 01:57:22,625 ERROR: Error from send_from_directory for vas95.png: 404 Not Found: The requested URL was not found on the server. If you entered the URL manually please check your spelling and try again. [in /var/www/proobrazovanie/data/www/ruproobrazovanie.ru/app/routes.py:658]
2025-06-18 01:57:23,026 INFO: Received request for avatar: vas95.png [in /var/www/proobrazovanie/data/www/ruproobrazovanie.ru/app/routes.py:643]
2025-06-18 01:57:23,027 INFO: Looking for avatar at: ./uploaded_files/avatars/vas95.png [in /var/www/proobrazovanie/data/www/ruproobrazovanie.ru/app/routes.py:645]
2025-06-18 01:57:23,027 INFO: Attempting to serve vas95.png via send_from_directory. [in /var/www/proobrazovanie/data/www/ruproobrazovanie.ru/app/routes.py:655]
2025-06-18 01:57:23,027 ERROR: Error from send_from_directory for vas95.png: 404 Not Found: The requested URL was not found on the server. If you entered the URL manually please check your spelling and try again. [in /var/www/proobrazovanie/data/www/ruproobrazovanie.ru/app/routes.py:658]
2025-06-18 01:57:23,034 INFO: Received request for avatar: ldrshza.png [in /var/www/proobrazovanie/data/www/ruproobrazovanie.ru/app/routes.py:643]
2025-06-18 01:57:23,034 INFO: Looking for avatar at: ./uploaded_files/avatars/ldrshza.png [in /var/www/proobrazovanie/data/www/ruproobrazovanie.ru/app/routes.py:645]
2025-06-18 01:57:23,034 INFO: Attempting to serve ldrshza.png via send_from_directory. [in /var/www/proobrazovanie/data/www/ruproobrazovanie.ru/app/routes.py:655]
2025-06-18 01:57:23,034 ERROR: Error from send_from_directory for ldrshza.png: 404 Not Found: The requested URL was not found on the server. If you entered the URL manually please check your spelling and try again. [in /var/www/proobrazovanie/data/www/ruproobrazovanie.ru/app/routes.py:658]
2025-06-18 02:02:39,950 INFO: Microblog startup [in /var/www/proobrazovanie/data/www/ruproobrazovanie.ru/app/__init__.py:58]
2025-06-18 02:02:40,031 INFO: Microblog startup [in /var/www/proobrazovanie/data/www/ruproobrazovanie.ru/app/__init__.py:58]
2025-06-18 02:02:40,138 INFO: Microblog startup [in /var/www/proobrazovanie/data/www/ruproobrazovanie.ru/app/__init__.py:58]
2025-06-18 02:02:40,173 INFO: Microblog startup [in /var/www/proobrazovanie/data/www/ruproobrazovanie.ru/app/__init__.py:58]
2025-06-18 23:44:28,288 INFO: Microblog startup [in /var/www/proobrazovanie/data/www/ruproobrazovanie.ru/app/__init__.py:58]
2025-06-18 23:44:28,315 INFO: Microblog startup [in /var/www/proobrazovanie/data/www/ruproobrazovanie.ru/app/__init__.py:58]
2025-06-18 23:44:28,325 INFO: Microblog startup [in /var/www/proobrazovanie/data/www/ruproobrazovanie.ru/app/__init__.py:58]
2025-06-18 23:44:28,322 INFO: Microblog startup [in /var/www/proobrazovanie/data/www/ruproobrazovanie.ru/app/__init__.py:58]
